### PR TITLE
Added base documentation

### PR DESCRIPTION
**Pull request by GeeH**

### CODE REVIEW

**Comment by EvanDotPro** [comment]
Thanks, Gary.

**Comment by GeeH** [comment]
Completely my pleasure Evan.

**Comment by Maks3w** [comment]
I think @EvanDotPro merged this by accident because merge to develop branch is missing

**Comment by akrabat** [comment]
@Maks3w: @GeeH asked him to only merge to master.

**Comment by GeeH** [comment]
I need to confirm with @mwop, previously I have only been merging these
docs to master and Matthew has taken care of the rest.

**Pull request merged**
